version: '3'

services:
  mysqlsrv:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cambio_service"
      MYSQL_USER: "victor"
      MYSQL_PASSWORD: "root2"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge