server:
  port: 8888
spring:
  application:
    name: config-server
  #Para Buscar as configurações nativas da API
  #profiles:
    #active:
    #- native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/11Victor/ConfigServer
          #username: username
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'
         